# Generated by Django 5.2.14 on 2026-06-28 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
