# Generated by Django 5.2.14 on 2026-05-18 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emprendedor_visitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuarios', models.ManyToManyField(related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_notificacion'],
            },
        ),
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_resenia', models.DateField(auto_now_add=True)),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='app.feria')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='app.visitante')),
            ],
            options={
                'ordering': ['-fecha_resenia'],
            },
        ),
    ]
