# Generated by Django 5.2.14 on 2026-05-18 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emprendedor_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='feria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='app.categoria'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicion', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_puestos', models.PositiveIntegerField()),
                ('tiene_conexion_electrica', models.BooleanField(default=False)),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='app.feria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
