# Generated by Django 5.2.14 on 2026-05-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoria_alter_feria_categoria_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_puesto', models.IntegerField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Lista_espera', 'Lista_espera'), ('Cancelada', 'Cancelada')], default='Lista_espera', max_length=20)),
                ('registrado_por', models.CharField(max_length=100)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_emprendedor', to='app.emprendedor')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_feria', to='app.feria')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['fecha_inscripcion'],
            },
        ),
    ]
